export const FETCH_FESTIVALS_REQUEST = "FETCH_FESTIVALS_REQUEST"
export const FETCH_FESTIVALS_SUCCESS = "FETCH_FESTIVALS_SUCCESS"
export const FETCH_FESTIVALS_FAILURE = "FETCH_FESTIVALS_FAILURE"

export const SWITCH_FESTIVAL_REQUEST = "SWITCH_FESTIVAL_REQUEST"
export const SWITCH_FESTIVAL_SUCCESS = "SWITCH_FESTIVAL_SUCCESS"
export const SWITCH_FESTIVAL_FAILURE = "SWITCH_FESTIVAL_FAILURE"

